Added last changed by user
Cinntax/pyenvisalink pull request #2
Opened 2016-10-13 09:33 UTC by jnimmo

Thanks for the pointers that made it very easy - this should do the trick although I don't have any user codes setup to test with on mine

2016-10-13 09:35 UTC, jnimmo commented on pyenvisalink/dsc_client.py
> +		return partitionNumber
Sorry dodgy spacing here fixed in the next commit

2016-10-14 03:26 UTC, Cinntax requested changes

2016-10-14 03:26 UTC, Cinntax commented on pyenvisalink/alarm_state.py
> +                                                      'exit_delay': False, 'entry_delay': False, 'last_changed_by_user': ''}}
What do you think about a last disarmed by user + last armed by user variables?

2016-10-14 03:26 UTC, Cinntax commented on pyenvisalink/dsc_client.py
> +	self.send_command(evl_Commands['PartitionKeypress'], str.format("{0}{1}", partitionNumber, keypresses[:6]))
I know this is incredibly nit-picky, but the indentation of the "self.send_command". doesn't match the comment above. Can you space it in 1 more?

2016-10-14 03:28 UTC, Cinntax commented
Thanks for your help on this!  A couple small things- I'll then do a release.

2016-10-14 06:35 UTC, jnimmo commented
Good spotting, hadn't figured out Git on desktop and the web editor was doing some funky stuff with tabs..
I've pulled it all back into desktop and de-tabbed so should be good now.
Also split into last_armed_by_user etc as that makes sense
Now I'm just not sure if you've got my latest code or if I have to somehow merge it - desktop is talking about a conflict.

2016-10-14 12:18 UTC, Cinntax commented
Shoot- doesn't look like I do have the latest code. I think you will have to do some merging on your end before I can on mine...

2016-10-14 20:32 UTC, jnimmo commented
Ok looks like I managed to merge it now sorry
Instead of if code in ['700','750'] you should now see
if code == '700':
....
elif code == '750':
and those other changes tidied up

2016-10-14 23:05 UTC, Cinntax approved these changes
Excellent- thanks!!  Are you ready for a release then?  I'm guessing so.

2016-10-14 23:05 UTC, merged

2016-10-15 01:38 UTC, jnimmo commented
Thanks very much, yeah ready for a release then I'll properly test out the HA changes - not sure what the requirements are for testing/lint etc but I guess I'll find out!

2016-10-15 03:05 UTC, Cinntax commented
Okay- 1.9 has been released!  Go ahead and reference that in the hass component.

2016-10-15 09:23 UTC, jnimmo commented
Awesome thanks, added that and mine has updated and working well